create table if not exists public.prediction_history (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  transformer_id text not null,
  failure_probability double precision not null,
  risk_level text not null,
  priority text not null,
  risk_score double precision not null,
  grid_impact double precision,
  weather_risk double precision,
  reasons jsonb not null default '[]'::jsonb,
  maintenance_recommendation text,
  crew_recommendation jsonb,
  reading jsonb not null default '{}'::jsonb,
  asset jsonb not null default '{}'::jsonb
);

create index if not exists prediction_history_checked_at_idx
  on public.prediction_history (checked_at desc);

alter table public.prediction_history enable row level security;

drop policy if exists prediction_history_insert_policy on public.prediction_history;
create policy prediction_history_insert_policy
  on public.prediction_history for insert
  to anon, authenticated
  with check (true);

drop policy if exists prediction_history_select_policy on public.prediction_history;
create policy prediction_history_select_policy
  on public.prediction_history for select
  to anon, authenticated
  using (true);